import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import "../../public/css/style.css";


const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bungah Dental Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif.variable} antialiased`}
      >
        <main className="mt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
